### ISSUE TITLE
feature request: allow access to user-defined metadata variables

### ISSUE THREAD

**Issue by the-drunk-coder** [hoene/libmysofa#100]
The SOFA standard allows for additional, user-defined metadata in the form of attributes and variables, as specified in paragraph 3.6.3 in the 0.6 specification:

> 3.6.3. User-defined metadata
User can provide additional metadata in terms of variables and attributes. User-defined variables must have explicitly defined dimensions using one of the SOFA dimensions. User-defined at- tributes can be global or can accompany variables.

As far as I can see, libmysofa currently reads global user-defined attributes, but not user-defined variables, which would come in handy for one of my current projects.

I've created a fork that reads additional global variables as well, would it be of interest to integrate this into the upstream ?

https://github.com/multimedia-eurecat/libmysofa/tree/non-standard-variables

**Comment by hoene** [comment]
Please add a test case.

 

 

Von: the-drunk-coder <notifications@github.com> 
Gesendet: Freitag, 17. Januar 2020 15:07
An: hoene/libmysofa <libmysofa@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [hoene/libmysofa] feature request: allow access to user-defined metadata variables (#100)

 

The SOFA standard allows for additional, user-defined metadata in the form of attributes and variables, as specified in paragraph 3.6.3 in the 0.6 specification:

3.6.3. User-defined metadata
User can provide additional metadata in terms of variables and attributes. User-defined variables must have explicitly defined dimensions using one of the SOFA dimensions. User-defined at- tributes can be global or can accompany variables.

As far as I can see, libmysofa currently reads global user-defined attributes, but not user-defined variables, which would come in handy for one of my current projects.

I've created a fork that reads additional global variables as well, would it be of interest to integrate this into the upstream ?

https://github.com/multimedia-eurecat/libmysofa/tree/non-standard-variables

**Comment by hoene** [comment]
For example, you could use a gunit test reading the file https://github.com/hoene/libmysofa/blob/778b2973bb6b6b675b3cdd99d9ce963c855dbb02/tests/example_dummy_sofa48.sofa, which has a custom attribute.

**Comment by hoene** [comment]
see #104
