### ISSUE TITLE
tests/example_dummy_sofa48_with_user_defined_variable fails

### ISSUE THREAD

**Issue by umlaeute** [hoene/libmysofa#112]
after a successful build i run:

~~~sh
$ cd tests
$  ./compare.sh example_dummy_sofa48_with_user_defined_variable
result  [ DiffNew {
    kind: 'N',
    path: [ 'Variables', 'GLOBALAdditionalVariable' ],
    rhs:
     { TypeName: 'double',
       Dimensions: [Array],
       DimensionNames: [Array],
       Values: [Array] } } ]
Diff 1
~~~

here's the output of the tests:  [tests.zip](https://github.com/hoene/libmysofa/files/4260958/tests.zip)

**Comment by hoene** [comment]
@umlaeute Is did issue fixed with your last commit?

**Comment by umlaeute** [comment]
no, not at all. #113 was only doing some cleanup of the test script, but not fixing anything.

the PR and this issue both happened because i was looking at `tests/`, but are otherwise unrelated.

**Comment by hoene** [comment]
This will not fix because it would require a complete HDF5 to JSON converter. This is not intended for this library as it would get too big.

**Comment by hoene** [comment]
see 2a7ab79f967bc36a8c3287530d68366e0cba4948
