### ISSUE TITLE
any plan for multichannel receivers? 

### ISSUE THREAD

**Issue by robaru** [hoene/libmysofa#115]
Hi! 
I would like to thank you for this project! We integrated your library into a projects of ours and the process was very smooth. 

I am wondering if there is a chance to have libmysofa supporting also SOFA files with multichannel receivers. It would be very helpful for us and our project! 

Thank you in advance.

Regards,
Roberto

**Comment by petibub** [comment]
Dear Roberto, 

currently many functions of libmysofa are optimized for R=2 and thus use manual distinction between channel 0 and 1. I don't know Christian's plan, but I guess that opening to R!=2 would be much work. 

If you just want to load a SOFA file with R>2, you could change in scr/check.c, line 66 " hrtf->R != 2" to " hrtf->R != my_number_of_receivers". I think that this should do it. But I'm afraid that many functions (like interpolate) won't work with such a loaded SOFA file.  

Good luck, Piotr

**Comment by robaru** [comment]
Dear Piotr,thank you for the reply and the suggestion! 

I will let you know how it goes.

Roberto

**Comment by hoene** [comment]
actually, use mysofa_load as it does not check for anything.
For example, use the tool mysofa2json to see your data.
