### ISSUE TITLE
HDF5: "Dimension #n Size" in "Layout: Data Layout Message (Versions 1 and 2)"

### ISSUE THREAD

**Issue by hoene** [hoene/libmysofa#116]
In specification https://portal.hdfgroup.org/display/HDF5/File+Format+Specification section "IV.A.2.i. The Data Layout Message" table "Layout: Data Layout Message (Versions 1 and 2)"
the entry "Dimension #n Size" seems to be wrong. Actually, it should be 
"Dimension #(n-1) Size" because n refers to Dimensionality and the table starts to count with 0.

FYI @gheber

**Comment by hoene** [comment]
https://github.com/hoene/libmysofa/blob/5c238dc820f16a21b4dce7e91df98431852146e7/src/hdf/dataobject.c#L526

**Comment by gheber** [comment]
Chris, you are quite right. It should read "Dimension 1 Size" through "Dimension #n Size." See for example IV.A.2.b. The Dataspace Message, the table under "Layout: Dataspace Message - Version 1". The file format specification is in "U language" not C or Fortran. The HDF5 Jira ticket is HDFFV-11079.
