### ISSUE TITLE
HDF5: III.G. Disk Format: Level 1G - Fractal Heap, Missing parts in the spec

### ISSUE THREAD

**Issue by hoene** [hoene/libmysofa#118]
In the HD5 spec, section "III.G. Disk Format: Level 1G - Fractal Heap" table "Fractal Heap Direct Block" field "Object Data":

It is unclear on what is stored here in which ways. It may refer to the section "IV.B. Disk Format: Level 2B - Data Object Data Storage", which was however never finished.

See in my code
https://github.com/hoene/libmysofa/blob/3a1e678f26bd9bfbf3cb23b5376aa9bb0944376a/src/hdf/fractalhead.c#L119 and following

FYI @gheber

**Comment by gheber** [comment]
Correct, the reference is "IV.B. Disk Format: Level 2B - Data Object Data Storage." It looks unfinished and not at all like Schubert's 8th ;-) The byte representation of what particular datatype family would you like to know more about?
