### ISSUE TITLE
HDF5: Contradicting implementation and spec

### ISSUE THREAD

**Issue by hoene** [hoene/libmysofa#119]
Reimplementing HDF5 for libmysofa, I found a couple of issues in where the current implementation differs from the document "HDF5 File Format Specification Version 3.0"

For example, 
in "Fields: Filter Description - Version 1", the "Filter Identification Value" is of type 0 in a recent HDF5 file ("_NCProperties = version=1|netcdflibversion=4.6.1|hdf5libversion=1.8.12". However, type 0 is "reserved".

Thus, the implemented software contradicts the spec.

FYI @gheber

**Comment by gheber** [comment]
Can you send us a sample file? I agree, if true, this would be a violation of the spec. Where did you get the file(s)?

**Comment by hoene** [comment]
It is opn https://github.com/hoene/libmysofa/blob/issue-58-receiver-positions-strange/share/MIT_KEMAR_normal_pinna.sofa
@f-brinkmann, should you specify with which versions on which OS this file has been produced.

**Comment by gheber** [comment]
I got the file and I'm looking at it. Which dataset (path?) has a filter description message with identification 0. I see several, but they all have identifications 8 (shuffle) and 1 (deflate).

**Comment by hoene** [comment]
I mistake on my side, sorry.
