### ISSUE TITLE
new SOFA files from sofacoustics.org do not work

### ISSUE THREAD

**Issue by richardpl** [hoene/libmysofa#120]
Newly uploaded sofa files from http://sofacoustics.org/data/database/ari/ looks to be unsupported by current version of libmysofa.

**Comment by robaru** [comment]
Same problem for the CIPIC database... 
The library returns the error MYSOFA_INVALID_RECEIVER_POSITIONS

**Comment by hoene** [comment]
I will have a look on it on the weekend.

**Comment by robaru** [comment]
Thank you!

**Comment by robaru** [comment]
Dear @hoene,
are there any updates on the bug? 

Thanks,
Roberto

**Comment by hoene** [comment]
@robaru working on it

**Comment by hoene** [comment]
Please test it with 
https://github.com/hoene/libmysofa/tree/issue-120-new-format

**Comment by robaru** [comment]
@hoene it appears to work! :) 

It outputs loads of stuff in the standard output but it appears to work well with subject_003.sofa from the CIPIC.

**Comment by the-drunk-coder** [comment]
@hoene can confirm, yay ! 

Tested with the files mentioned above, a file from CIPIC and some older files of my team that didn't work in the past. They all work now ! 

Plus, if the `RoomType` is set to `reverberant` it works as well (not sure if that was related at all).

Thanks !
