### ISSUE TITLE
SADIE II - BRIR not loading

### ISSUE THREAD

**Issue by the-drunk-coder** [hoene/libmysofa#133]
I remember there was a problem with some SADIE files in the past (#55), which has been fixed. Now I've been trying another SADIE file, this time a BRIR, and loading fails with code 10004 (`MYSOFA_INVALID_ATTRIBUTES`). 

It's this one: https://www.york.ac.uk/sadie-project/Resources/SADIEIIDatabase/D1/D1_BRIR_SOFA.zip

Not sure if this is because they are `MultispeakerBRIR` instead of `SimpleFreeFieldHRIR`. 

Are they expected to work in the first place ? Maybe I missed something but I haven't found any hint in the docs that they aren't...

**Comment by hoene** [comment]
sorry for the late answer. Indeed, libmysofa is only for HRTFs.

**Comment by the-drunk-coder** [comment]
Just out of interest, is there a reason it wouldn't work with BRIRs ? 

I mean, if I change the attribute in the SOFA file to `SimpleFreeFieldHRTF` it works just fine, and in general I'm using plenty of "roomy" measurements wrapped in SOFA files ...

**Comment by hoene** [comment]
@the-drunk-coder It should be possible to use the low-level API, e.g. mysofa_load(filename, err);
Then, HRTF-related checks and calculations are not done.
