### ISSUE TITLE
Compilation tests fail on s390x

### ISSUE THREAD

**Issue by tanertas** [hoene/libmysofa#140]
I'm trying to compile v1.1 on Alpine Linux s390x but it fails during tests after compilation.
Full build log is here:
https://gitlab.alpinelinux.org/terra/aports/-/jobs/209430/raw

**Comment by hoene** [comment]
@tanertas The link is not working anymore...

**Comment by hoene** [comment]
@tanertas Please provide further information till April 1st, 2021.
