### ISSUE TITLE
Loading pretty large SOFA file fails silently - is there a size limit ?

### ISSUE THREAD

**Issue by the-drunk-coder** [hoene/libmysofa#155]
Hi,

we recently created a SOFA file that has 2702 measurements of 8192 samples length, amounting to ~355MB. Pretty large.

Trying to load this SOFA fails with error 10000. There's no debug out that I could relate to the error.

Is there some limit that prevents libmysofa from loading files of this size ?

Best,

**Comment by petibub** [comment]
Dear Drunk Coder, 

can you load one of these: http://sofacoustics.org/data/database/sbsbrir/

Regards, 
Piotr

**Comment by hoene** [comment]
Because of various misuse attempts, all variables have some kind of maximal limit based on a typical use patterns.

I assume your HRTF is just another attempt to crash libmysofa? 

You may compile libmysofa with the VDEBUG define to see, where it finally fails.

**Comment by the-drunk-coder** [comment]
@hoene No it was a legit attempt, no "bad" intentions here ... just an experiment with up-sampling that returned a very large SOFA file ... 

@petibub the SBSBRIR files don't load either, but there's a difference ... 

- The SBSBRIR fail at `mysofa_check`, with error `MYSOFA_READ_ERROR` or `10004`
- the file I loaded fails at `mysofa_load` with error `MYSOFA_INVALID_FORMAT` or `10000`

I compiled with VDEBUG but there's no explicit error or warning, so it's hard to figure out where things go wrong.

The last messages before failure are:

```
[...]/hdf/dataobject.c:484: data layout 2
[...]/hdf/dataobject.c:521: dimensionality 4
[...]/hdf/dataobject.c:530: CHUNK 8953
[...]/hdf/dataobject.c:533: 541
[...]/hdf/dataobject.c:533: 1
[...]/hdf/dataobject.c:533: 1639
[...]/hdf/dataobject.c:533: 8

```

**Comment by hoene** [comment]
@the-drunk-coder  You may try to remove or modify the lines

```
        if (size > 0x10000000)
          return MYSOFA_INVALID_FORMAT; // LCOV_EXCL_LINE
```

 https://github.com/hoene/libmysofa/blob/master/src/hdf/dataobject.c#L546

**Comment by the-drunk-coder** [comment]
Commented out the two lines, now the file loads (takes a while though). Guess I'll set it to a reasonable limit ...

Thanks !

**Comment by hoene** [comment]
Fine. Just tell me the new limit here and I will add it to the next version.
You may use mysofa_load instead of mysofa_open. Then, the interpolation structures are not precalculated.
