### ISSUE TITLE
Load fail due to Object Header Continuation Message offset size

### ISSUE THREAD

**Issue by gooderist** [hoene/libmysofa#158]
Hello, I am getting a MYSOFA_UNSUPPORTED_FORMAT on a file where the Continuation Message contains an offset value of `0x1766c48`. This is larger than the `0x1000000` hard-coded at `dataobject.c:884` which results in unsupported format being returned.

If I change the condition to `if (offset > 0x2000000 || ...` then the file load proceeds seemingly without any other issues. My question is if this is a bad thing to do or if the original value `0x1000000` is just arbitrary? Thank you.

**Comment by hoene** [comment]
The value of 0x1000000 is just a safety measure and can be increased based on new usage patterns.
We will update it in the next release.

**Comment by gooderist** [comment]
Thank you!
