### ISSUE TITLE
libmysofa issues with clang + lld + ucrt

### ISSUE THREAD

**Issue by neheb** [hoene/libmysofa#159]
Related: https://github.com/msys2/MINGW-packages/pull/8606

The issue is that clang does not like MYSOFA_EXPORT on redeclarations. Only on first declaration.

What's the consensus on fixing this? Installing the mysofa_export.h header?

**Comment by hoene** [comment]
@neheb  Can this issue be closed?

**Comment by neheb** [comment]
Guess so.
