### ISSUE TITLE
Delays are in samples instead of seconds as described in Readme

### ISSUE THREAD

**Issue by not-availabIe** [hoene/libmysofa#161]
Current documentation
```
float leftIR[filter_length]; // [-1. till 1]
float rightIR[filter_length];
float leftDelay;          // unit is sec.
float rightDelay;         // unit is sec.

mysofa_getfilter_float(hrtf, x, y, z, leftIR, rightIR, &leftDelay, &rightDelay);
```
My test shows that the delays are (and should be, imho) in samples. SOFA 1.0 also requires the delays to always be in samples in SOFA files. This function doesn't convert unit of delays into seconds.

**Comment by hoene** [comment]
@not-availabIe  Did you use mysofa_getfilter_float or mysofa_getfilter_short.
float is seconds.
short is in samples.

**Comment by not-availabIe** [comment]
@hoene I used float

**Comment by hoene** [comment]
@not-availabIe 
1) The API of the libmysofa must be changed - I have to reject your wish to ensure interoperability with all other users.
2) If you want to report an bug (which I do not believe that it exists here), please provide an failing unit test case as a merge request.
3) Libmysofa reads and interprets the SOFA files according to the AES. The libmysofa API does not relates the AES SOFA specification but is independent and define here.

**Comment by not-availabIe** [comment]
@hoene Got it. The difference in the AES standard and the AES SOFA spec on the unit of delays is confusing but not much can be done here.

**Comment by not-availabIe** [comment]
@hoene But if the unit of delays are assumed to be seconds, why in /src/hrtf/resample.c the delays are scaled by the sampling rate?

**Comment by hoene** [comment]
@not-availabIe  My schedule is full thus I cannot provide any implementation support here. If you need further help or explanations, please write your request to info@symonics.com Thank you for your understand.
