### ISSUE TITLE
release version confusion

### ISSUE THREAD

**Issue by acbits** [hoene/libmysofa#172]
The tag is 1.2.1, but the libmysofa.so built is actually libmysofa.so.1.1.0, and the deb package built is also named libmysofa-1.1.0-Linux.deb. 

Was that intentional naming or a bug?

**Comment by hoene** [comment]
it is a bug that will be fixed with 1.2.2

**Comment by acbits** [comment]
I am assuming that you would name the libmysofa.so version as 1.2.2 to match the tag?

**Comment by kwizart** [comment]
SO version are usually unrelated to the package (or project) version.
Here are some answer: https://stackoverflow.com/questions/7553184/how-to-do-versioning-of-shared-library

That been said, it can be an indication. (say if libmysofa 2.x is introduced breaking ABI with libmysofa.so.1)

**Comment by acbits** [comment]
True, but many packages follow a convention of stamping the release version onto the shared files. I think _glibc_ does it that way as it is easier to track what release a library belongs to.

**Comment by umlaeute** [comment]
i think it's the other way round (or at least should be): many packages follow the convention of [semantic versioning](https://semver.org) for the package version, even though strictly speaking it is only required of the soname version.
