### ISSUE TITLE
Large file load failure, error code:10000 due to "gunzip error -3 incorrect header check"

### ISSUE THREAD

**Issue by not-availabIe** [hoene/libmysofa#178]
I compiled with VDEBUG when loading a file containing HRIRs with dimension 12722-by-2-by-4410 and got the errors below.
Following other raised issues, I have commented out all file size limits that I found in the c codes.  (https://github.com/hoene/libmysofa/issues/155). The file size is 750MB.
The file is able to load without error when I reduced the HRIR dimension to 12722-by-2-by-2500. The threshold seems to be somewhere between 2500 and 2600 in my case. Reducing the 1st dimension also helps.
The file can be loaded and saved without problem with the latest MATLAB sofa API, so unlikely to be a corrupted file.

error log below:
..\src\hdf\btree.c:247: 00008D39 TREE
..\src\hdf\btree.c:271: elements 1558935 size 8
..\src\hdf\btree.c:295: start 0 0
..\src\hdf\btree.c:295: start 1 0
..\src\hdf\btree.c:295: start 2 0
..\src\hdf\btree.c:303:  data at 299C1392 len 10914249
..\src\hdf\gunzip.c:30:  gunzip error -3 incorrect header check
..\src\hdf\btree.c:326:    gunzip -3 0 12471480

The problem seems to be related to the gunzip used to decompress the SOFA file. Hopefully I can find later versions of gunzip to replace the one used in libmysofa for some testing.

edit: gunzip lib included is already the latest version.

**Comment by hoene** [comment]
@not-availabIe May you share the file with me? This would help significantly.

**Comment by hoene** [comment]
Why does the program try to access data at 0x299C1392 if the file is only 750 MByte large?

**Comment by not-availabIe** [comment]
@hoene Of course, thanks. Please find the download link here: https://wetransfer.com/downloads/3355b223c285f9b2c31511978fc532ac20220218172413/67b271de8949600193ce0925197df91f20220218172426/96a444

**Comment by not-availabIe** [comment]
@hoene I can reupload the SOFA file if the link expires.

**Comment by hoene** [comment]
please provide the file again.
