### ISSUE TITLE
Extremely large release artifact size

### ISSUE THREAD

**Issue by grobe0ba** [hoene/libmysofa#180]
Like most people in my area, I have a very limited internet connection,
an unstable ADSL link over 60+ year old copper. I'm lucky to get 500Kbps
download. Downloading 237.6MiB of tests for 376KiB of actual code borders
on the ludicrous. (Assuming nothing else attempts to use the connection,
that's over an hour of downloading.)

Please consider moving your testing material into a separate repository which
can be included via git modules, or move the test material into Git LFS,
which Github can be set to not include into release artifacts.

In many cases, having the test materials in the same place as the code is
an entirely sensible location. However, with the very large size of that
material in this project, it makes more sense to me to have it separated. For
the people who actually develop the code, it is still readily available,
but for those that just need release code to build and go, testing probably
isn't one of their needs. If  they need to do some debugging, they still
have the ability to fetch the needed materials.

**Comment by hoene** [comment]
lack of relevance
