### ISSUE TITLE
This needs better information included to encourage wide use.

### ISSUE THREAD

**Issue by doggodanubus** [hoene/libmysofa#188]
What Fedora has and other distributions most likely have give no information to folk that might investigate it further to see if it is interesting and useful to them.

Something like a "This is a library to decode and parse  3D audio binaural audio files. With this you can read standardized and do.....

This needs finished out with what a programmer can do with it and with the data it extracts or produces. 

I see this all to often with projects that never go anywhere. I'm not a programmer and have no clue how to use this. Just want to see something that might make cool things get wider use.

**Comment by hoene** [comment]
@doggodanubus Please follow the [code of conduct](https://github.com/hoene/libmysofa/blob/main/CODE_OF_CONDUCT.md
) if you participating here.
