### ISSUE TITLE
license/copyright of third-party/ components

### ISSUE THREAD

**Issue by umlaeute** [hoene/libmysofa#19]
the `third-party/` folder contains a number of libraries, supposedly (according to the folder-name) written (and copyrighted) by 3rd parties.
unfortunately, apart from zlib (which contains at least *some* information in the `zlib.h` header) it is unclear who are the copyright holders and under which license the various files are distributed.

**Comment by hoene** [comment]
I moved the windows library to an separate folder.
pthread binary has been removed.

**Comment by umlaeute** [comment]
hmm, moving to another foldert address the problem that there is no licensing/copyright information.

**Comment by hoene** [comment]
For sys/time
see
https://stackoverflow.com/questions/25615571/how-to-use-sys-time-h-in-window

**Comment by umlaeute** [comment]
i'm not doubting that there are good reasons to include the headers.

my issue is that you are lacking copyright and license information.

**Comment by hoene** [comment]
@petibub 

Found license of third_party/sys It is LGPL

@umlaeute 
Now all license questions should be solved...
