### ISSUE TITLE
Delay Dimensions M,R

### ISSUE THREAD

**Issue by hoene** [hoene/libmysofa#190]
[EAC Individualized HRTF Synthesis](https://github.com/davircarvalho/Individualized_HRTF_Synthesis) was just [released as a standalone app](https://github.com/davircarvalho/Individualized_HRTF_Synthesis/releases/latest), so [generating personalized SOFAs](https://i.imgur.com/q6rRoLz.png) is now a lot easier.

However, I'm having trouble converting them to OpenAL Soft MHR using :
`makemhr.exe -r 44100 -i "EAC_44.1kHz.sofa" -o "EAC_44.1kHz-44100.mhr"`
If I use the makemhr from [openal-soft-1.22.2](https://openal-soft.org/openal-binaries/openal-soft-1.22.2-bin.zip) (latest stable release at the moment), I get this error:
```
Generating "EAC_44.1kHz-44100.mhr"
Using 2 threads.
Reading HRTF data from EAC_44.1kHz.sofa...
Unexpected delay attribute: _Netcdf4Coordinates = (null)
Unsupported delay dimensions: M,R
```
And if I use makemhr from [openal-soft-1.20.1](https://openal-soft.org/openal-binaries/openal-soft-1.20.1-bin.zip) (the last version that has worked for me with other SOFAs), I get this:
```
Generating "EAC_44.1kHz-44100.mhr"
Reading HRTF data from EAC_44.1kHz.sofa...
Error: Could not load EAC_44.1kHz.sofa: Unsupported format
```

_Originally posted by @ThreeDeeJay in https://github.com/hoene/libmysofa/issues/186#issuecomment-1264698746_

**Comment by hoene** [comment]
please report this bug at openal not here.

**Comment by ThreeDeeJay** [comment]
Fair enough, I'll check with kcat then 👌 
and by the way, [here's the SOFA and script](https://www.dropbox.com/s/2tnrrorobutg2ai/%5BOpenAL%20Soft%5D%20SOFA%20to%20MHR%20test.zip?dl=1) I used to replicate this issue.

**Comment by ThreeDeeJay** [comment]
My thoughts exactly, I'll relay the message.
