### ISSUE TITLE
Cache hit does not set the return code

### ISSUE THREAD

**Issue by sh7dm** [hoene/libmysofa#196]
See https://github.com/hoene/libmysofa/blob/main/src/hrtf/easy.c#L140 . If cache is available, err is not set.

Memory might be uninitialized thus causing random errors. This could be fixed by users if they initialize the var by default

**Comment by hoene** [comment]
please check the following bug fix: https://github.com/hoene/libmysofa/commit/5d15d92ed1de2e1666fb7d8b10721e2c64a782b1

**Comment by sh7dm** [comment]
Not ready to recompile PipeWire with this revision now. However, doesn't appear to fix what I expected to get fixed. Let me just submit a fix PR.
