### ISSUE TITLE
source missing for `sofa2json` test

### ISSUE THREAD

**Issue by umlaeute** [hoene/libmysofa#20]
the `tests/s2j` folder contains a number of binaries without source-code
- `sofa2json`
- `libnetcdf_c++4.so.1.0.3`

i'd suggest to:
- remove all binaries
- add the source of `sofa2json` 
   - and build it when building `libmysofa`
- drop the dependency on the no-longer-existing `libnetcdfc++4` packge (to the docker image can be used without having to manually provide an outdated and unmaintained binary blob)

**Comment by umlaeute** [comment]
side note: all binaries are for `amd64`.
this makes it impossible to run the tests on any other architecture (I just recently had an [issue](https://bugs.debian.org/#865344) with the well-known, well-tested and generally beloved `libsndfile` library that had a bug exposed only on `arm`-architectures)

**Comment by hoene** [comment]
https://github.com/hoene/libmysofa/blob/master/tests/README
