### ISSUE TITLE
Installing libmysofa on Windows for use from a cmake project via find_package

### ISSUE THREAD

**Issue by lmtanco** [hoene/libmysofa#206]
Hello!
I am trying to use libmysofa via find_package from a multiplatform cmake project. 

In macOS everything works perfectly. I install libmysofa, via cmake, make and make install, and then I can configure my project which depends on the system installation of libmysofa, using: 

`find_package(mysofa CONFIG 1.3 REQUIRED)`, and this creates the target I want to use: `mysofa::mysofa-static`

This is a link to the full [CMakeLists.txt ](https://github.com/GrupoDiana/BRTLibrary/blob/cmake/CMakeLists.txt). In macOS, my project configures and compiles just fine. 

My question is: **Can I do the same thing in Windows?** I have tried but the INSTALL project in the Visual Studio Solution (I am using VStudio 2022) fails giving a "The sequence has no elements" error. 

This is a screenshot of my CMake cache in the libmysofa configuration on Windows: 

![image](https://github.com/hoene/libmysofa/assets/1093084/8dff3921-7e92-4c17-9826-3db28b931f0e)

Many many thanks in advance! 

Luis.

**Comment by hoene** [comment]
This web site is for bug tickets not for feature requests.
