### ISSUE TITLE
Error when RoomType is not default

### ISSUE THREAD

**Issue by HaHeho** [hoene/libmysofa#207]
[This HRIR](https://publications.rwth-aachen.de/record/807373/files/Kemar_HRTF_sofa.sofa) specifies "hemi-anechoic" as its RoomType. This leads to `MYSOFA_INVALID_ATTRIBUTES` due to https://github.com/hoene/libmysofa/blob/0b6c96541cbabcaf4ace1a0f48d3aef548be448d/src/hrtf/check.c#L61-L64

The issue in https://github.com/hoene/libmysofa/issues/205 also prevents that specific data set from being loaded. But I believe the issue presented here is clear without a valid data set for testing.

According to [the SimpleFreeFieldHRIR 1.0 standard](https://github.com/sofacoustics/SOFAtoolbox/blob/d48f10cdbf1abe2d0385feb66ffe7713d0beb68d/SOFAtoolbox/conventions/SimpleFreeFieldHRIR_1.0.csv#L17C18-L17C28) the default parameter is "free field", but I could not find a limitation to the other values. Does this exist or did it use to in an older 

I am not sure a limitation of RoomType to exclusively "free field", "reverberant", and "shoebox" should exist there. I can't imagine a situation where this should prevent the load of an HRIR set. If there is a (soft) reason for the check, then maybe a warning would suffice?

**Comment by hoene** [comment]
fixed with #209
