### ISSUE TITLE
run tests outside of docker

### ISSUE THREAD

**Issue by umlaeute** [hoene/libmysofa#21]
the `sofa2json` test currently depends on docker.

since the test is a blackbox (see #20), it is unclear why it needs to be encapsulated in a container.

most real-world test suites i've seen so far can be run fine without virtualization/containerization (though i see the merits of running them in containers anyhow: e.g. because you don't trust any pre-compiled binary blob where you cannot inspect the code for maliciousness; otoh, docker provides [little protection](https://de.wikipedia.org/wiki/Docker_%28Software%29#Sicherheitsrisiken) against attacks anyhow).

it would be great if the tests could be run on an ordinary system, even if it doesn't support virtualisation (think: tseting whether the library behaves correctly on older `arm` architectures)

**Comment by hoene** [comment]
docker has been removed...
