### ISSUE TITLE
unknown license for SOFA files

### ISSUE THREAD

**Issue by umlaeute** [hoene/libmysofa#22]
the files in [`/tests`](https://github.com/hoene/libmysofa/blob/master/tests/) have no license information.

instead the README says that they were downloaded from some 3rd party website. i couldn't find any license information on that website as well.

since there is no license, the files are automatically under *All rights reserved*, thus
>  you have no permission from the creators of the software to use, modify, or share [...]

**Comment by hoene** [comment]
All licenses have been collect now...
