### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Dekomoro** [hoene/libmysofa#223]
Would it be possible to see a new release some time soon? I've noticed it's been a bit since the last release, and some changes that seem somewhat important have landed. Me and a few others I know would possibly like to see this in linux distributions. If there are planned changes that are not landed that are expected to be pushed before the next release feel free to close this issue.

**Comment by kwizart** [comment]
There is a github action script that has cut a release, but the git tag is set to latest which is not easy to set as a version.
It should be bump to v1.3.3 to follow the previous convention.

Also the internal PROJECT_VERSION version according to CMakeLists.txt is still 1.3.2 . It should be bump to 1.3.3

**Comment by kwizart** [comment]
I went to provide a git snapshot in fedora, but it should be easier if a tag is provided upstream
Specially as pipewire seems to rely on newer libmysofa...
https://bugzilla.redhat.com/show_bug.cgi?id=2316036
