### ISSUE TITLE
Unit tests are failing with version 1.3.2+ (including latest)

### ISSUE THREAD

**Issue by kwizart** [hoene/libmysofa#224]
Building the package suceeded on fedora 39 and onward, but the units tests are failing
Here is a full build.log (non-official scratch build)
https://koji.fedoraproject.org/koji/taskinfo?taskID=124272338 (edited)

```
43/43 Test #36: TU-Berlin_QU_KEMAR_anechoic_radius_0.5_1_2_3_m ....   Passed   16.60 sec

65% tests passed, 15 tests failed out of 43

Total Test time (real) =  16.65 sec

The following tests FAILED:
	  4 - H20_44K_16bit_256tap_FIR_SOFA (Failed)
	  5 - MIT_KEMAR_large_pinna (Failed)
	  6 - MIT_KEMAR_normal_pinna (Failed)
	  7 - MIT_KEMAR_normal_pinna.old (Failed)
	  8 - dtf_nh2 (Failed)
	  9 - hrtf_c_nh898 (Failed)
	 31 - CIPIC_subject_003_hrir_final (Failed)
	 32 - FHK_HRIR_L2354 (Failed)
	 33 - LISTEN_1002_IRC_1002_C_HRIR (Failed)
	 34 - Pulse (Failed)
	 35 - Tester (Failed)
	 37 - TU-Berlin_QU_KEMAR_anechoic_radius_0.5m (Failed)
	 38 - example_dummy_sofa48 (Failed)
	 39 - TestSOFA48_netcdf472 (Failed)
	 40 - example_dummy_sofa48_with_user_defined_variable (Failed)
```

**Comment by Dekomoro** [comment]
I can not reproduce on CachyOS or Arch Linux. Is it possible fedora has an issue here?

**Comment by umlaeute** [comment]
We are running the test-suite on Debian as well, and it runs nicely on a variety of architectures: https://ci.debian.net/packages/libm/libmysofa/

in any case, looking at your build.log, it seems that all the errors come from `node` not being able to parse the json files.
maybe this is a problem with your node installation, rather than of libmysofa?

**Comment by kwizart** [comment]
Someone suggested that's because the ctests are run with parallelism ('-j6') and from one test is overwritten by the others.

I confirm that using ctest with -j1 works locally (x86_64) for all tests.

Running a scratch build to confirm (on-going) https://koji.fedoraproject.org/koji/taskinfo?taskID=124309085

**Comment by hoene** [comment]
ctest -j8 work now for me.
