### ISSUE TITLE
MYSOFA_INVALID_FORMAT for files larger than 0x10000000

### ISSUE THREAD

**Issue by enzodesena** [hoene/libmysofa#225]
(Probably) not an issue, but here goes. Loading Kemar_HRTF_sofa.sofa from [this](https://publications.rwth-aachen.de/record/807373) Aachen high-resolution Kemar HRTF dataset throws MYSOFA_INVALID_FORMAT at line 550 of data object.h:
```
        if (size > 0x10000000)
          return MYSOFA_INVALID_FORMAT; // LCOV_EXCL_LINE
```
This is clearly due to the size of this particular SOFA file being larger than 0x10000000. Where is the 0x10000000 limit coming from? Increasing the limit to 0x100000000 (i.e. 16 times larger) fixes it. Does that break the library somewhere else? Thanks.

**Comment by hoene** [comment]
solved with #226
