### ISSUE TITLE
Change build version of so files

### ISSUE THREAD

**Issue by hoene** [hoene/libmysofa#23]
API shall not change...

**Comment by umlaeute** [comment]
The idea is that the library's `soversion` uses *Semantic Versioning*.

[Here'](http://pusling.com/blog/?p=352) is an example on how to implement sonames with CMake.

The proper documentation on API/ABI versioning can be found under [Semantic Versioning](http://semver.org/).

Also note, that semantic versioning of an API/ABI ist not necessarily the same thing as the "release versions" of your software package (though for library-only packages it might make sense to couple them closely).
