### ISSUE TITLE
stlil some more license information to clarify

### ISSUE THREAD

**Issue by umlaeute** [hoene/libmysofa#25]
thanks for all the updates on licenses.

there's still a few issues, clarifications required:
- is `./share/MIT_KEMAR_normal_pinna.sofa` covered by the `tests/LICENSE.MIT_KEMAR_large_pinna` as well?
- `tests/Pulse.*` are covered by `CC-BY-4.0`, but who is the copyright holder? this is especially important, as the `CC-BY` license requires attribution, but who is to attribute?
- `tests/FHK_HRIR_L2345` are covered by `CC-BY-SA-3.0`, but who is the copyright holder? this is especially important, as the `CC-BY` license requires attribution, but who is to attribute?

**Comment by hoene** [comment]
I will remove the MIT normal pinna from the shared folder and replace it by a HRTF without the requirement of attribution.

**Comment by umlaeute** [comment]
actually I think that the `LICENSE.MIT_KEMAR_large_pinna` is [fine from the Debian perspective](http://sources.debian.net/src/csound/1:6.08.0~dfsg-1/debian/copyright/#L214).
