### ISSUE TITLE
default.sofa (and why is it installed?)

### ISSUE THREAD

**Issue by umlaeute** [hoene/libmysofa#27]
it seems that the file `share/default.sofa` is nowhere actually used in the code.
at least, a quick `rgrep default.sofa *` only returns its enumeration in the `CMakeList.txt`.

instead the symlinked-to file `MIT_KEMAR_normal_pinna.sofa` is referenced directly in some of the test sources. (I guess the original idea was to keep the code independent of the actually used sofa-file, but it seems that this was forgotten).

more interestingly though, is the question why the files in `share/` are actually *installed* (when running `make install`). afaict, they are not used by anything outside the test suite...

**Comment by hoene** [comment]
default.sofa is useful if somebody wants to have 3D audio but does not have his own SOFA file.
Then, using a default HRTF still provides reasonable results. 
The sofa file in share is for the user and app not for the library.

**Comment by hoene** [comment]
Actually, I would extend the API.
If you give a NULL pointer as file name to the open/load commands, they shall load the default.sofa file.

**Comment by hoene** [comment]
Fixed with
https://github.com/hoene/libmysofa/commit/95ed39a41078866f871c1d7547262cdd874ec3d9

**Comment by umlaeute** [comment]
btw, did you no that [you can automatically close github-issues via your commit message](https://help.github.com/articles/closing-issues-via-commit-messages/)?
