### ISSUE TITLE
Add a pkg-config file

### ISSUE THREAD

**Issue by jamrial** [hoene/libmysofa#38]
libmysofa should install a pkg-config file alongside the library and headers. This is especially useful (and in a way necessary) for static builds, where zlib and libm need to be explicitly linked to if support is compiled in.
Something simple like:

> prefix=xxx
> exec_prefix=${prefix}
> libdir=${exec_prefix}/lib
> includedir=${prefix}/include
> 
> Name: libmysofa
> Version: 0.7
> Description: Reader for AES SOFA files to get better HRTFs 
> URL: https://github.com/hoene/libmysofa
> Libs: -L${libdir} -lmysofa
> Libs.Private: -lm -lz
> Cflags: -I${includedir}

With -lm and -lz being included only if needed (as detected by CMake) should be enough.

**Comment by hoene** [comment]
Do you want to provide a patch?

**Comment by jamrial** [comment]
I'm not familiar enough with CMake, otherwise I'd have indeed done it myself and sent a pull request. Sorry.

**Comment by hoene** [comment]
I am not an expert with pkg-config.
May this help you to get a pc files for libmysofa?
http://www.kaizou.org/2014/11/typical-cmake-project/

**Comment by Reino17** [comment]
At this moment FFmpeg still manually links libmysofa **and** its dependencies.
This works, but I had a look to have it use the pkg-config file instead:
```patch
diff --git a/configure b/configure
index 9fa1665..856bddf 100755
--- a/configure
+++ b/configure
@@ -6000,7 +6000,8 @@ enabled libmfx            && { check_pkg_config libmfx libmfx "mfx/mfxvideo.h" M
                                { require libmfx "mfx/mfxvideo.h" MFXInit "-llibmfx $advapi32_extralibs" && warn "using libmfx without pkg-config"; } }
 enabled libmodplug        && require_pkg_config libmodplug libmodplug libmodplug/modplug.h ModPlug_Load
 enabled libmp3lame        && require "libmp3lame >= 3.98.3" lame/lame.h lame_set_VBR_quality -lmp3lame $libm_extralibs
-enabled libmysofa         && require libmysofa "mysofa.h" mysofa_load -lmysofa $zlib_extralibs
+enabled libmysofa         && { check_pkg_config libmysofa libmysofa mysofa.h mysofa_load ||
+                               require libmysofa mysofa.h mysofa_load -lmysofa $zlib_extralibs; }
 enabled libnpp            && { check_lib libnpp npp.h nppGetLibVersion -lnppig -lnppicc -lnppc ||
                                check_lib libnpp npp.h nppGetLibVersion -lnppi -lnppc ||
                                die "ERROR: libnpp not found"; }
```
This works too, **but** only if '_libmysofa.pc_' is setup right! It needs `-lm` and `-lz`, as James already pointed out.

I believe something like this is needed:
```patch
diff --git a/libmysofa.pc.cmake b/libmysofa.pc.cmake
index f5413a9..0b2fb7a 100644
--- a/libmysofa.pc.cmake
+++ b/libmysofa.pc.cmake
@@ -8,5 +8,5 @@ libdir=${prefix}/lib
 Libs: -L${libdir} -lmysofa
 Cflags: -I${includedir}
 
-#Libs.private:
+Libs.private: @PKG_CONFIG_MATH@ @PKG_CONFIG_ZLIB@
 #Requires.private:
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index 3c3c663..3fd8224 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -14,7 +14,9 @@ configure_file (config.h.in ${PROJECT_SOURCE_DIR}/src/config.h)
 
 if(NOT MSVC)
   find_library(MATH m)
+  set(PKG_CONFIG_MATH "-lm")
   include(FindZLIB)
+  set(PKG_CONFIG_ZLIB "-lz")
 else()
   set(MATH "")
   find_program(NUGET nuget)
```
I'm still rather new to all of this. I don't know exactly how everything works in '_CMakeList.txt_'. The set commands are obviously in the wrong place, because `Libs.private:` remains empty in '_libmysofa.pc_'.
I have no doubt you can work this out nicely.
