### ISSUE TITLE
Sofa file from SADIE fails to load

### ISSUE THREAD

**Issue by knopp** [hoene/libmysofa#42]
Link to file

https://www.york.ac.uk/sadie-project/Resources/Binaural/SOFA/SADIE_KU100_DFC_256_order_fir_48000.sofa

mysofa_check aborts at the following condition:
|| hrtf->ReceiverPosition.values[1] > 0

the actual value is positive (0.0900000035), everything else checks out.

**Comment by hoene** [comment]
Left and right ears are switched in the file.

Always tthe guys from UK. Mirroring it all up. Always driving on the wrong side of the street...

Do you want to provide a fix to correct left and right channels within libmysofa?

Is the file then still working?
