### ISSUE TITLE
No longer able to cross compile with Mingw after ea9ce56

### ISSUE THREAD

**Issue by Zeranoe** [hoene/libmysofa#51]
I'm unable to cross compile with Mingw after ea9ce56dc1983261a6938cb99581c84ade0a09ef:

`CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
MATH`

This is due to `find_library(MATH m)`, which should not be used for WIN32 targets.

libccd also ran into this issue: https://github.com/danfis/libccd/issues/2

**Comment by hoene** [comment]
please test again...

**Comment by Zeranoe** [comment]
It seems to get past the MATH check now, but fails to find zlib.h during compilation.

zlib was found during the initial configure at DZLIB_ROOT because it is in a non standard location.

I suspect this is due to a lack of `include_directories(${ZLIB_INCLUDE_DIRS})`.

If you'd like you can close this bug report and I can open another specifically for the zlib issue now.

**Comment by hoene** [comment]
Please check cb8dc1d9df66309e862b5473ce9eb6db9542e283

**Comment by Zeranoe** [comment]
Works as expected, and I'm able to use ZLIB_ROOT. Thank you for resolving these.

**Comment by hoene** [comment]
Now we have new complaints
https://github.com/hoene/libmysofa/issues/56

**Comment by Zeranoe** [comment]
The other issue was resolved.
