### ISSUE TITLE
Unpredictable behavior with some sofa files

### ISSUE THREAD

**Issue by Bk8** [hoene/libmysofa#54]
I was testing this library on OsX on real time but some times the library start to get some really clipped values with huge exponentials. I was using HRIR_CIRC360 KU100.sofa from the Thk database you can download the file here:
http://sofacoustics.org/data/database/thk/

And I was able to reproduce the bug with this code, some times you have to run it more that one time to start to get huge random values. Finally I tried to test the Sadie database but libmysofa 
is not able to load it. The link to sadie hrtf: https://www.york.ac.uk/sadie-project/database.html. Thanks I hope you can help me to fix this issues.

```
int main (int argc, char* argv[])
{

    int filter_length;
    int err;
    struct MYSOFA_EASY *hrtf = NULL;
    
    hrtf = mysofa_open("HRIR_CIRC360 KU100.sofa", 44100, &filter_length, &err);
    
    std::cout <<"Phi max: "+std::to_string(hrtf->lookup->phi_max)<< std::endl;
    std::cout <<"Phi min: "+std::to_string(hrtf->lookup->phi_min)<< std::endl;
    std::cout <<"Phi max: "+std::to_string(hrtf->lookup->theta_max)<< std::endl;
    std::cout <<"Phi min: "+std::to_string(hrtf->lookup->theta_min)<< std::endl;
    std::cout <<"Rad max: "+std::to_string(hrtf->lookup->radius_max)<< std::endl;
    std::cout <<"Rad min: "+std::to_string(hrtf->lookup->radius_min)<< std::endl;
    std::cout <<"Samples: "+std::to_string(hrtf->hrtf->N)<< std::endl;
    std::cout <<"Num meassures: "+std::to_string(hrtf->hrtf->M)<< std::endl;
    std::cout <<"Num receiver: "+std::to_string(hrtf->hrtf->R)<< std::endl;
    std::cout <<"Num emitters: "+std::to_string(hrtf->hrtf->E)<< std::endl;
    std::cout <<"Sampling Rate: "+std::to_string(hrtf->hrtf->DataSamplingRate.values[0])<< std::endl;
    
    if(hrtf==NULL)
        return err;
    
    float leftIR[filter_length];
    float rightIR[filter_length];
    float leftDelay;          
    float rightDelay;         
    
    
    std::cout <<"coord num: "+std::to_string(hrtf->hrtf->SourcePosition.elements);
    
    for(int t=0; t<10000;t++) //Rapid and multiple changes as in real time
    for(int i=0; i<hrtf->hrtf->SourcePosition.elements;i+=3)
    {
        double x=hrtf->hrtf->SourcePosition.values[i];
        double y=hrtf->hrtf->SourcePosition.values[i+1];
        double z=hrtf->hrtf->SourcePosition.values[i+2];
        
        mysofa_getfilter_float(hrtf, x, y, z,&leftIR[0], &rightIR[0], &leftDelay, &rightDelay);
        
        for(int j=0; j<filter_length;j++)
        {
            if(leftIR[j]>1 || rightIR[j]>1)
            {
                std::cout <<"Clipping"<< std::endl;
                std::cout <<std::to_string(leftIR[j])<< std::endl;
                std::cout <<std::to_string(rightIR[j])<< std::endl;
            }
        }
    }
    
    mysofa_close(hrtf);
    return 0;
}
```

**Comment by Bk8** [comment]
I was using a fork of zlib, with zlib version 1.2.11 is harder to make it fail. But I still get random cilped values but at least they are smaller and I have to make it run 100000.

**Comment by Bk8** [comment]
I looked to the code and I'm not sure where exactly the error is, but the error is inside mysofa_neighborhood  or mysofa_interpolate. Removing all the code that is necessary to perform interpolations and just reading the hrir using:

`copyArrayWeighted(fir, easy->hrtf->DataIR.values + nearest * size, size, 1);`

removes the unwanted and unpredictable behavior.

**Comment by hoene** [comment]
So, is this an error which happens only from time to time?

**Comment by hoene** [comment]
Which file are you using "HRIR_CIRC360 KU100.sofa"? Where do I find it?

**Comment by hoene** [comment]
I can confirm some problems running it with valgrind:

==22202== Conditional jump or move depends on uninitialised value(s)
==22202==    at 0x402993: main (test.cpp:50)
==22202== 
==22202== Conditional jump or move depends on uninitialised value(s)
==22202==    at 0x4029B5: main (test.cpp:50)
==22202== 
            if(leftIR[j]>1 || rightIR[j]>1)

This should not happen...

**Comment by Bk8** [comment]
Thanks I'm going to test it again. Here is the link to the sofa file http://sofacoustics.org/data/database/thk/HRIR_CIRC360.sofa. And the error was happening some times not always on real time or just making a lot of calls to the library, but it looks like this commit solves the issues. Also sofa files with AES 69 SOFA are not compatible? I was trying to open this sofa files  https://www.york.ac.uk/sadie-project/database.html, but I the library was not able to. Maybe because AES69-2015 has no backward compatibility with AES 69 SOFA? Thanks a lot!!

**Comment by hoene** [comment]
Ok, this bug is solved.
The next bug is https://github.com/hoene/libmysofa/issues/55
