### ISSUE TITLE
Files from https://www.york.ac.uk/sadie-project/database.html do not open

### ISSUE THREAD

**Issue by hoene** [hoene/libmysofa#55]
I was trying to open this sofa files https://www.york.ac.uk/sadie-project/database.html, but I the library was not able to. Maybe because AES69-2015 has no backward compatibility with AES 69 SOFA? Thanks a lot!!

**Comment by hoene** [comment]
@Bk8
I just tested:
D1_44K_16bit_256tap_FIR_SOFA.sofa  D1_48K_24bit_256tap_FIR_SOFA.sofa  D1_96K_24bit_512tap_FIR_SOFA.sofa
hoene@dev4:~/git/libmysofa/D1_HRIR_SOFA$ mysofa2json D1_44K_16bit_256tap_FIR_SOFA.sofa 

so, what is not working precisely?

**Comment by gooderist** [comment]
I haven't tested the entire database but D2_44K_16bit_256tap_FIR_SOFA.sofa and H3_44K_16bit_256tap_FIR_SOFA.sofa appear to be rejected because `RoomType` is set to `Reverberant - Acoustically treated listening room.` instead of `free field`.

**Comment by the-drunk-coder** [comment]
Experiencing the same, only that in my case it not only doesn't open, but crash on occasion: #86 #87

**Comment by hoene** [comment]
see #120
