### ISSUE TITLE
Potential typo on delays resampling in resample.c

### ISSUE THREAD

**Issue by PyrApple** [hoene/libmysofa#65]
Shouldn't the line 
`` hrtf->DataIR.values[i] /= factor; `` 
be 
`` hrtf->DataDelay.values[i] /= factor; `` 
in [resample.c](https://github.com/hoene/libmysofa/blob/2c742a321eb30cd1d07d8510edafcfa0a06090e1/src/hrtf/resample.c#L81) ?

**Comment by hoene** [comment]
Yes, every good.

**Comment by hoene** [comment]
merge
