### ISSUE TITLE
removing .sofa files for a lightweight library

### ISSUE THREAD

**Issue by PyrApple** [hoene/libmysofa#8]
Dear Hoene, my thanks for the lib. Would you mind removing some of the .sofa files in the test folder (e.g. all but one) for a more lightweight package? (>100Mo at the time)

**Comment by hoene** [comment]
Actually, for testing, I could download them on the fly from https://www.sofaconventions.org/
Only tester.sofa is unique.

**Comment by hoene** [comment]
fixed

**Comment by PyrApple** [comment]
Considering the creation of a HomeBrew formula for libmysofa, the library is still > 50Mo because of the .sofa files. Such a large lib doesn't make much sense. Is there a reason to include all these files?

**Comment by seebk** [comment]
Cloning and downloading the lib from Git really is a pain due to the huge binary files.

@hoene I would propose to remove all binary files in the repository. Then add a small script which allows the user to download the binary files when they are actually needed.
