### ISSUE TITLE
How to copy MYSOFA_LOOKUP?

### ISSUE THREAD

**Issue by mgeier** [hoene/libmysofa#80]
First of all, thanks for this library, I especially like it's nicely modular API!

I would like to use `mysofa_lookup()` from multiple threads in parallel.

As stated in the `README`, the library isn't threadsafe (and it really isn't, I tried it and got very strange behavior).

In order to use it with multiple threads, I would like to make copies of the `MYSOFA_LOOKUP` structure to avoid those problems.

Is there a way to copy those?

I guess I could call `mysofa_lookup_init()` multiple times to get copies, but I would like to avoid needing access to the `MYSOFA_HRTF` struct at this point.
The reason for this is that I'm loading all data from `MYSOFA_HRTF` into my own data structure and I'm deleting my `MYSOFA_HRTF` as soon as I've obtained `MYSOFA_LOOKUP` from it.

**Comment by hoene** [comment]
It is unclear on what you need. Performance or memory saving? What is your use case?

**Comment by mgeier** [comment]
This is the use case: https://github.com/SoundScapeRenderer/ssr/pull/165

I'm implementing a real-time dynamic binaural renderer that can render multiple sources at once.
The filter selection and the convolution should happen in parallel if there are multiple sources (and if the user chose to use multiple audio threads).

**Comment by mgeier** [comment]
This has been resolved in #81, which made `mysofa_lookup()` reentrant.
