### ISSUE TITLE
Avoid allocations in hyperrect_duplicate()?

### ISSUE THREAD

**Issue by mgeier** [hoene/libmysofa#85]
`hyperrect_duplicate()` is used in `kd_nearest()`:

https://github.com/hoene/libmysofa/blob/e07edb39e9ecc796127cd748ada4a4bac88cb5d2/src/hrtf/kdtree.c#L422-L426

The original `kdtree` library allows an arbitrary number of dimensions at runtime, therefore it needs to dynamically allocate memory at this point.

In `libmysofa` however, only 3-dimensional KD-trees are used:

https://github.com/hoene/libmysofa/blob/5ca7409c3784f6656bf0cb1af648a31489d5bf36/src/hrtf/lookup.c#L71

Therefore, the dynamic allocation could be (and IMHO should be) avoided.

Or did I miss something?

**Comment by hoene** [comment]
merged. Thank you for your contribution
