### ISSUE TITLE
Trying to load invalid SOFA file leads to crash.

### ISSUE THREAD

**Issue by the-drunk-coder** [hoene/libmysofa#86]
Loading a SOFA file with an invalid format usually returns the `MYSOFA_INVALID_FORMAT` state (10000), as it's expected. 

In my case, though, if frequently causes a crash.

I'm trying to load the SOFA file with:
`hrtf = mysofa_open_no_norm(sofaPath.toStdString().c_str(), lastSampleRate, &sofa_filter_length, &sofa_err);`

Frequently, the program crashes with (includes some debug output):
```
/Users/my.user/my_repositories/MySofaProject/dependencies/libmysofa/src/hrtf/reader.c:101:  Units=metre
/Users/my.user/my_repositories/MySofaProject/dependencies/libmysofa/src/hrtf/reader.c:101:  DIMENSION_LIST=R,C,I
/Users/my.user/my_repositories/MySofaProject/dependencies/libmysofa/src/hrtf/reader.c:101:  Units=metre
/Users/my.user/my_repositories/MySofaProject/dependencies/libmysofa/src/hrtf/reader.c:101:  Type=cartesian
/Users/my.user/my_repositories/MySofaProject/dependencies/libmysofa/src/hrtf/reader.c:101:  DIMENSION_LIST=I,C
EurecatSimpleSOFAPanner(2448,0x101dfb5c0) malloc: *** error for object 0x7fff9cad1000: pointer being freed was not allocated
EurecatSimpleSOFAPanner(2448,0x101dfb5c0) malloc: *** set a breakpoint in malloc_error_break to debug
```

The debugger points to `easy.c`, line 195.

The SOFA file is from the SADIE II database, i've attached it for convenience.

**Comment by the-drunk-coder** [comment]
[D1_48K_24bit_0.3s_FIR_SOFA.sofa.zip](https://github.com/hoene/libmysofa/files/3845917/D1_48K_24bit_0.3s_FIR_SOFA.sofa.zip)

Here's the file !

**Comment by PyrApple** [comment]
(Not solving the issue of the non-informative feedback)

The file fails to open because 
1) RoomType attribute is not "free field" (but "Reverberant - Acoustically treated listening room.")
2) ReceiverPosition is "reversed"

Matlab fix:
```
% load file
s = SOFAload('D1_48K_24bit_0.3s_FIR_SOFA.sofa');

% fix file
s.GLOBAL_RoomType = 'free field';
s.ReceiverPosition(1,2) = -s.ReceiverPosition(1,2);
s.ReceiverPosition(2,2) = -s.ReceiverPosition(2,2);

% save file
SOFAsave('D1_48K_24bit_0.3s_FIR_SOFA_fixed.sofa', s, 9);
```

Agreed regarding the lack of feedback, will tackle this at some point.

**Comment by hoene** [comment]
typically, mysofa_check shall identify this issue

**Comment by hoene** [comment]
Do you use multiple threads to access libmysofa?

**Comment by the-drunk-coder** [comment]
Hmm not that I can see but I'll have a deeper look at it. 

It doesn't crash at all when the SOFA file is successfully loaded, which leads me to assume that concurrent access might not be the problem ...

**Comment by the-drunk-coder** [comment]
I just checked, there's only one thread accessing the `MYSOFA_EASY` pointer. The crash happens on first loading attempt (if it happens). 

I'm using `mysofa_open_no_norm` to open the sofa file.

**Comment by PyrApple** [comment]
Try loading with the updated [added-multithread-test](https://github.com/hoene/libmysofa/tree/added-multithread-test) branch: 6c61df947df63f7cdd31c6529fd29e96d636baa0 should fix that bug.

**Comment by the-drunk-coder** [comment]
Hmm that seems to work ... thanks !

**Comment by the-drunk-coder** [comment]
> typically, mysofa_check shall identify this issue

Just for clarification, `mysofa_check` can only be used after `mysofa_load`, which already gives an error code ... is there any advantage in doing the subsequent call to `mysofa_check` ?

**Comment by PyrApple** [comment]
> Just for clarification, ```mysofa_check``` can only be used after ```mysofa_load```

At least it is intended that way yes.

> which already gives an error code

In your exemple, it is ```mysofa_check``` that returns the ```MYSOFA_INVALID_ATTRIBUTES (err = 1004)``` value, not ```mysofa_load``` ...

> is there any advantage in doing the subsequent call to mysofa_check ?

... hence yes

**Comment by the-drunk-coder** [comment]
Thanks :)
