### ISSUE TITLE
Some SOFA files are not supported (without informative feedback)

### ISSUE THREAD

**Issue by the-drunk-coder** [hoene/libmysofa#87]
The SOFA file I attached to #86 can't be read with libmysofa. 

The reference C++ implementation of the SOFA API processes it without problems. Is there types of SOFA files that aren't compatible with libmysofa? 

The feedback (error code 10000) isn't really informative, so I don't really have a clue why loading this SOFA file fails (or what I'd need to change to make it load).

**Comment by the-drunk-coder** [comment]
Just saw that this duplicated #55 somewhat, except for the part about the more specific feedback.

**Comment by hoene** [comment]
I added the following error messages
`+       MYSOFA_INVALID_ATTRIBUTES,
+       MYSOFA_INVALID_DIMENSIONS,
+       MYSOFA_INVALID_DIMENSION_LIST,
+       MYSOFA_INVALID_COORDINATE_TYPE,
+       MYSOFA_ONLY_EMITTER_WITH_ECI_SUPPORTED,
+       MYSOFA_ONLY_DELAYS_WITH_IR_OR_MR_SUPPORTED,
+       MYSOFA_ONLY_THE_SAME_SAMPLING_RATE_SUPPORTED,
+       MYSOFA_RECEIVERS_WITH_RCI_SUPPORTED,
+       MYSOFA_RECEIVERS_WITH_CARTESIAN_SUPPORTED,
+       MYSOFA_INVALID_RECEIVER_POSITIONS,
+       MYSOFA_ONLY_SOURCES_WITH_MC_SUPPORTED
`
