### ISSUE TITLE
build problem + test problem

### ISSUE THREAD

**Issue by FreaIsDead** [hoene/libmysofa#95]
i followed the installation guide. I'm using MXLinux.
After building with latest cmake i do test, but they all fails.
Also if i try to compile a simple C program:

"#include "mysofa.h"
#include "stddef.h"

int filter_length;
int err;
struct MYSOFA_EASY *hrtf = NULL;

int openSofa(char *name)
{
    hrtf = mysofa_open(name, 48000, &filter_length, &err);
    if (hrtf == NULL)
        return err;
}"

It says: 
"$gcc example.c -I/home/frea/Documenti/c2s/libmysofa-master/src/hrtf/
/usr/bin/ld: /tmp/ccdRjjsL.o: in function 'openSofa':
prova.c:(.text+0x2a): undefined reference to 'mysofa_open'
collect2: error: ld returned 1 exit status

what i am doing wrong?

**Comment by hoene** [comment]
-Ldir -lmysofa
