### ISSUE TITLE
.sofa written with netCDF 4.6.1 not loading

### ISSUE THREAD

**Issue by vsaari** [hoene/libmysofa#97]
Hi, we already talked on Friday and here's the ticket as we discussed. I have a .sofa file that has been written with netCDF 4.6.1 which is not loaded by libmysofa. The issue is in the superblock version of the underlying HDF5 file. NetCDF has moved to using superblock version 0 and libmysofa seems to only support superblock versions 2 and 3. An example file is attached. It contains just unit impulses as impulse responses but is enough for testing the file read.
[example_dummy_sofa48.zip](https://github.com/hoene/libmysofa/files/4053826/example_dummy_sofa48.zip)

**Comment by hoene** [comment]
"Since release 4.4.1, netCDF-4 files created will have superblock version 0 instead of superblock version 2"
The file format specification is given in https://portal.hdfgroup.org/display/HDF5/File+Format+Specification
I will need help with the code review.

**Comment by vsaari** [comment]
I took a look at the specification and the current source code for the lib, it seems that the superblock version 0 has some extra fields which mostly seem to always contain the same value so they won't have an effect on the implementation. However it seems that the entry to the group graph is provided as a different format( root group object header vs. symbol table entry) so this will probably be of some work to fix. Additionally I suspect that there can be some differences in Data Object Header Message versions which then would need extra work. How should we proceed on this and what kind of help would you need with the code ?

**Comment by hoene** [comment]
@vsaari  Please make a code review

**Comment by vsaari** [comment]
I will do the review during this week

**Comment by hoene** [comment]
solved with 99bb06b765680c07f2d9007bf98db5c586763c4a
